// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwndzkihjpekwrkrkmoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bmR6a2loanBla3dya3JrbW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDM4MjEsImV4cCI6MjA3MTYxOTgyMX0.RmebMnOMQFaZ3WXruULs4OjWk60uLjQh57d4oTQc6JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});